# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9ec5247c-ede7-49ee-b7f9-cd1aca664747";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B54C-9F6B";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7c4ff044-d2e2-4efe-a8ed-d5dd36250c2f";
      fsType = "ext4";
    };  

  fileSystems."/media/data" =
    { device = "/dev/disk/by-label/data";
      fsType = "ext4";
    };
  
 swapDevices =
    [ { device = "/dev/disk/by-uuid/c5b5d6e8-0018-4d3e-b6e8-7ee2f0e0ef75"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
