#!/usr/bin/env bash

col=$(tput cols)
title="Fetching your configs"
end="Press any key to start xserver .."
space="		"
space1="	    "

f1() {
	for (( i=1; i<=$col; i++ ));
	do
		printf "$1";
	done;
}


clear
f1 =;
echo
echo
printf `tput bold`"%*s\n" $(((${#title}+$col)/2)) "$space $title"`tput sgr0`
echo
f1 =;
echo
echo 
if ! [[ -d ~/.config/awesome ]] ; then
	echo "Awesome WM";
	echo
	git clone --depth=1 https://github.com/creator54/awesome-configs -b nixos_test ~/.config/awesome;
	ln -s ~/.config/awesome/.xinitrc ~/.xinitrc;
	echo "symlinked xinitrc";
	f1 +;
fi;

if ! [[ -d ~/.local/share/omf ]] ; then
	echo "Fish";
	echo
	if curl -s https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish ; then
		echo "Switching theme: mzish";
		git clone https://github.com/creator54/mzish -b test ~/.local/share/omf/themes/mzish;
		fish -c "omf theme mzish";
	fi
	f1 +;
fi;

if ! [[ -d ~/.config/kitty ]] ; then
	echo "Kitty";
	echo 
	mkdir ~/.config/kitty && wget https://raw.githubusercontent.com/Creator54/dotfiles/master/kitty/kitty.conf -P ~/.config/kitty/;
	f1 +;
fi;

if ! [[ -d ~/.SpaceVim.d ]] ; then
	echo "SpaceVim";
	echo
	if curl -sLf https://spacevim.org/install.sh | bash ; then
		echo "Switching theme to SpaceVim";
		sed -i 's/gruvbox/SpaceVim/' ~/.SpaceVim.d/init.toml;
		echo "adding cutom plugins"
		{
			echo "# custom plugins {{{"
			echo "[[colorizer]]"
			echo "name = 'lilydjwg/colorizer'"
			echo "merged = 0"
			echo "# }}}"
		} >> ~/.SpaceVim.d/init.toml;
	fi
	f1 +;
fi;

echo "All done !"
f1 =;
echo
echo

if [[ $? == 0 ]] ; then
	printf "%*s\n" $(((${#end}+$col)/2)) "$space1 $end";
	read key
	if [ ${#key} -eq 0 ] ; then
		startx &> /dev/null;
	fi
else
	exit;
fi
clear;

